elasticsearch:
  image: elasticsearch:1.7
  ports:
    - "9200:9200"
    - "9300:9300"

zookeeper:
  expose:
   - "2181"
   - "2888"
   - "3888"
  image: jplock/zookeeper

mesosmaster:
  image: containersol/mesos-master:0.25.0-0.2.70.ubuntu1404
  expose:
    - "5050"
  environment:
    MESOS_QUORUM: '1'
    MESOS_ZK: 'zk://zookeeper:2181/mesos'
  links:
    - zookeeper

mesosslave:
  image: containersol/mesos-agent:0.25.0-0.2.70.ubuntu1404
  privileged: true
  environment:
    MESOS_RESOURCES: 'ports(*):[5000-5000,31000-32000]; cpus(*):0.2; mem(*):256; disk(*):200'
    MESOS_PORT: '5051'
    MESOS_MASTER: 'zk://zookeeper:2181/mesos'
    MESOS_SWITCH_USER: 'false'
    GLOG_v: '1'
    MESOS_EXECUTOR_REGISTRATION_TIMEOUT: '5mins'
    MESOS_CONTAINERIZERS: 'docker,mesos'
    MESOS_ISOLATOR: 'cgroups/cpu,cgroups/mem'
    MESOS_LOG_DIR: '/var/log'
    MESOS_LOGGING_LEVEL: 'INFO'
    MESOS_WORK_DIR: '/tmp/mesos'
  pid: "host"
  volumes:
    - /var/lib/docker:/var/lib/docker
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /usr/local/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock
  links:
    - mesosmaster
    - zookeeper
    - elasticsearch

logstashscheduler:
  image: mesos/logstash-scheduler
  expose:
    - "9092"
  links:
    - zookeeper
    - elasticsearch
  environment:
    JAVA_OPTS: '-Dmesos.logstash.web.port=9092 -Dmesos.logstash.framework.name=logstash -Dmesos.logstash.logstash.heap.size=128 -Dmesos.logstash.executor.heap.size=64 -Dmesos.logstash.volumes=/var/log/mesos -Dmesos.zk=zk://zookeeper:2181/mesos -Dmesos.logstash.elasticsearchDomainAndPort=172.17.0.1:9200'

kibana:
  image: kibana:4.1
  ports:
    - "5601:5601"
  links:
    - elasticsearch
